version: "3.9"
services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/go/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    